### ISSUE TITLE
/schema/plugin/spring-plugin.xsd is missing on http://www.springframework.org

### ISSUE THREAD

**Issue by p-himik** [spring-projects/spring-plugin#16]
README has an example on how to include spring-plugin.xsd in context configuration files.
However an attempt to access it on http://www.springframework.org/schema/plugin/spring-plugin.xsd yields HTTP 404 error.

**Comment by tgkprog** [comment]
Needs to be on your local class path. http://stackoverflow.com/questions/5875021/what-is-the-use-of-xsischemalocation might help. Look for the file on the spring site and keep resources folder. Should have been inside one of  the spring jars

**Comment by p-himik** [comment]
Oh, yes, thanks. Seems that my IDE hadn't downloaded the jar right away when I've included the dependency.
