### ISSUE TITLE
Use a correct execution environment (JavaSE-1.6) in manifests

### ISSUE THREAD

**Issue by shanmukhm** [spring-projects/spring-plugin#24]
The property `Bundle-RequiredExecutionEnvironment: J2SE-1.6` can be seen in 'MANIFEST.MF' after spring-plugin bundles are generated. I'm using OSGi in Felix for my application. When I deploy my application in Tomcat. I'm getting the folowing error: 
`org.osgi.framework.BundleException: Unresolved constraint in bundle spring-plugin-core [79]: Execution environment not supported: J2SE-1.6`
Actually there is no execution environment called 'J2SE-1.6' 
It should be changed to 'JavaSE-1.6' or the property should be removed.
link to refer: http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Ftasks%2Fpde_compilation_env.htm

**Comment by olivergierke** [comment]
Pull request submitted in #25.

**Comment by olivergierke** [comment]
PR merged, thanks again! :)

**Comment by shanmukhm** [comment]
No Problem
